In [3]:
import numpy as np

In [11]:
data_zip = np.load("../training_data/ac_20250820_224210.npz", allow_pickle=True)

In [12]:
list(data_zip.keys())

['hand_idx',
 'disc_idx',
 'called_idx',
 'game_state',
 'called_discards',
 'flat_idx',
 'returns',
 'advantages',
 'old_log_probs',
 'game_ids',
 'step_ids',
 'actor_ids',
 'flat_policies',
 'game_outcomes_obj']

In [14]:
np.min(data_zip["flat_idx"])

np.int64(-1)

In [15]:
np.max(data_zip["flat_idx"])

np.int64(151)

In [6]:
data_zip["hand_idx"]

array([[1, 6, 13, ..., 31, 33, 34],
       [1, 6, 10, ..., 29, 33, 34],
       [1, 6, 10, ..., 29, 29, 34],
       ...,
       [3, 4, 35, ..., 20, 21, -1],
       [3, 4, 35, ..., 18, 20, 21],
       [3, 4, 35, ..., 20, 21, 29]], shape=(395076, 14), dtype=object)

array([-0.596147  , -0.60216874, -0.6082512 , -0.6143952 , -0.6206012 ,
       -0.62686986, -0.6332019 , -0.6395979 , -0.64605844, -0.6525843 ,
       -0.65917605, -0.6658344 , -0.67256004, -0.67935354, -0.6862157 ,
       -0.6931472 ,  1.1685674 ,  1.1803712 ,  1.192294  ,  1.2043375 ,
        1.2165024 ,  1.2287904 ,  1.2412024 ,  1.2537397 ,  1.2664038 ,
        1.2791958 ,  1.2921169 ,  1.3051686 ,  1.3183521 ,  1.3316689 ,
        1.3451201 ,  1.3587071 ,  1.3724314 ,  1.3862944 ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.5901856 , -0.596147  , -0.60

In [15]:
data_zip["returns"]

array([0., 0., 0., ..., 0., 0., 0.], shape=(7808,), dtype=float32)